-- +migrate Up
CREATE TABLE IF NOT EXISTS operation_approvals (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  ticket VARCHAR(96) NOT NULL,
  domain VARCHAR(64) NOT NULL DEFAULT '',
  scope_cluster_id BIGINT UNSIGNED NULL,
  scope_project_id BIGINT UNSIGNED NULL,
  scope_team_id BIGINT UNSIGNED NULL,
  namespace VARCHAR(128) NOT NULL DEFAULT '',
  environment VARCHAR(32) NOT NULL DEFAULT '',
  resource VARCHAR(64) NOT NULL DEFAULT '',
  resource_id VARCHAR(128) NOT NULL DEFAULT '',
  action VARCHAR(64) NOT NULL DEFAULT '',
  context_json LONGTEXT NOT NULL,
  reason VARCHAR(255) NOT NULL DEFAULT '',
  status VARCHAR(32) NOT NULL DEFAULT 'pending',
  request_by BIGINT UNSIGNED NOT NULL DEFAULT 0,
  review_by BIGINT UNSIGNED NOT NULL DEFAULT 0,
  expires_at TIMESTAMP NULL,
  consumed_at TIMESTAMP NULL,
  consumed_by BIGINT UNSIGNED NOT NULL DEFAULT 0,
  replay_count INT NOT NULL DEFAULT 0,
  replay_at TIMESTAMP NULL,
  replay_by BIGINT UNSIGNED NOT NULL DEFAULT 0,
  replay_code VARCHAR(64) NOT NULL DEFAULT '',
  replay_message VARCHAR(255) NOT NULL DEFAULT '',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_operation_approvals_ticket (ticket),
  KEY idx_operation_approvals_domain (domain),
  KEY idx_operation_approvals_scope_cluster_id (scope_cluster_id),
  KEY idx_operation_approvals_scope_project_id (scope_project_id),
  KEY idx_operation_approvals_scope_team_id (scope_team_id),
  KEY idx_operation_approvals_namespace (namespace),
  KEY idx_operation_approvals_environment (environment),
  KEY idx_operation_approvals_resource (resource),
  KEY idx_operation_approvals_resource_id (resource_id),
  KEY idx_operation_approvals_action (action),
  KEY idx_operation_approvals_status (status),
  KEY idx_operation_approvals_expires_at (expires_at),
  KEY idx_operation_approvals_consumed_at (consumed_at),
  KEY idx_operation_approvals_created_at (created_at)
);

CREATE TABLE IF NOT EXISTS operation_audits (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  domain VARCHAR(64) NOT NULL DEFAULT '',
  scope_cluster_id BIGINT UNSIGNED NULL,
  scope_project_id BIGINT UNSIGNED NULL,
  scope_team_id BIGINT UNSIGNED NULL,
  namespace VARCHAR(128) NOT NULL DEFAULT '',
  environment VARCHAR(32) NOT NULL DEFAULT '',
  resource VARCHAR(64) NOT NULL DEFAULT '',
  resource_id VARCHAR(128) NOT NULL DEFAULT '',
  action VARCHAR(64) NOT NULL DEFAULT '',
  operator_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
  status VARCHAR(32) NOT NULL DEFAULT 'success',
  code VARCHAR(64) NOT NULL DEFAULT '',
  message VARCHAR(255) NOT NULL DEFAULT '',
  request_summary_json LONGTEXT NOT NULL,
  result_summary_json LONGTEXT NOT NULL,
  diagnostics_json LONGTEXT NOT NULL,
  approval_ticket VARCHAR(96) NOT NULL DEFAULT '',
  latency_ms BIGINT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_operation_audits_domain (domain),
  KEY idx_operation_audits_scope_cluster_id (scope_cluster_id),
  KEY idx_operation_audits_scope_project_id (scope_project_id),
  KEY idx_operation_audits_scope_team_id (scope_team_id),
  KEY idx_operation_audits_namespace (namespace),
  KEY idx_operation_audits_environment (environment),
  KEY idx_operation_audits_resource (resource),
  KEY idx_operation_audits_resource_id (resource_id),
  KEY idx_operation_audits_action (action),
  KEY idx_operation_audits_operator_id (operator_id),
  KEY idx_operation_audits_status (status),
  KEY idx_operation_audits_code (code),
  KEY idx_operation_audits_approval_ticket (approval_ticket),
  KEY idx_operation_audits_created_at (created_at)
);

-- +migrate Down
DROP TABLE IF EXISTS operation_audits;
DROP TABLE IF EXISTS operation_approvals;
